version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "9000:9000"
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
