version: '2'
volumes:
  backend-storage:
  postgres-storage:
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fpm
    volumes: 
      - backend-storage:/srv/app/storage
    ports:
      - "9000:9000"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    # volumes: 
    #   - backend-storage:/srv/app/storage
    depends_on:
      - backend
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: scoops
