FROM php:7.4-fpm-alpine

COPY docker-scripts/install-php-extensions /usr/local/bin

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd xdebug

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY . /srv/app
VOLUME
